<!DOCTYPE html>
<html lang="pt-br" >
    <head>
        <meta charset="UTF-8">
        <title>Contato - Barbearia Alura</title>

        <link rel="stylesheet" href="Reset_css.css">
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <div class="caixa">
                <h1 ><img src="img/logo.png" alt="logo da Barbearia Alra"></h1>

                <nav>
    	            <ul>
    	                <li><a href="index.php">Home</a></li>
    	                <li><a href="produtos.php">Produtos</a></li>
    	                <li><a href="contato.php">Contato</a></li>
    	            </ul>
                </nav>
            </div>
        </header>