<!DOCTYPE html>
<html lang="pt-br" >
    <head>
        <meta charset="UTF-8">
        <title>Barbearia Cris</title>

        <link rel="stylesheet" href="Reset_css.css">
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
        <div class="loginimg"><a href="login.php"><img src="img/login.png" width ="60px""></a></div>
            <div class="caixa">
                <h1 ><img src="img/bg.jpg" alt="logo da Barbearia Alra" width="178px"></h1>

                <nav>
    	            <ul>
    	                <li><a href="?">Tabela horários</a></li>
    	                <li><a href="index.php">Home</a></li>
    	                <li><a href="produtos.php">Produtos</a></li>
    	                <li><a href="contato.php">Contato</a></li>
    	            </ul>
                </nav>
            </div>
        </header>